// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9IXbAOThpctkOGFlJuRNYsD6t6v8MWS8',
    appId: '1:494939840306:web:06aca6d8ef36237737c12b',
    messagingSenderId: '494939840306',
    projectId: 'todoapp-a6d21',
    authDomain: 'todoapp-a6d21.firebaseapp.com',
    storageBucket: 'todoapp-a6d21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIATPGBrqG2qlhvB81oWI-a7SDBx8TCZY',
    appId: '1:494939840306:android:f0b5d739f620652637c12b',
    messagingSenderId: '494939840306',
    projectId: 'todoapp-a6d21',
    storageBucket: 'todoapp-a6d21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ-_9h4FkaB8o8dsdWcEiOielqORHyhGM',
    appId: '1:494939840306:ios:89a3cb51c66295d637c12b',
    messagingSenderId: '494939840306',
    projectId: 'todoapp-a6d21',
    storageBucket: 'todoapp-a6d21.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ-_9h4FkaB8o8dsdWcEiOielqORHyhGM',
    appId: '1:494939840306:ios:89a3cb51c66295d637c12b',
    messagingSenderId: '494939840306',
    projectId: 'todoapp-a6d21',
    storageBucket: 'todoapp-a6d21.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9IXbAOThpctkOGFlJuRNYsD6t6v8MWS8',
    appId: '1:494939840306:web:32a4c002c7aea95237c12b',
    messagingSenderId: '494939840306',
    projectId: 'todoapp-a6d21',
    authDomain: 'todoapp-a6d21.firebaseapp.com',
    storageBucket: 'todoapp-a6d21.firebasestorage.app',
  );
}
